version: '3'
services:
    es:
        image: elasticsearch:6.4.1
        container_name: es
        environment:
            - discovery.type=single-node
        ports:
            - 9200:9200
            - 9300:9300
    be: 
        container_name: be
        build: .
        depends_on:
            - es
        ports:
            - 5000:5000
    fe:
        container_name: fe
        image: nginx:1.19.0
        
        volumes:
            - "/home/asher/Desktop/foodtrucks/project/flask-app/static:/usr/share/nginx/html"
            - "/home/asher/Desktop/foodtrucks/project/flask-app/templates/index.html:/usr/share/nginx/html/index.html"
            - "/home/asher/Desktop/foodtrucks/nginx.conf:/etc/nginx/nginx.conf"
        depends_on:
            - be
        ports:
            - "80:80"
  

 
    
     
      
